name: Zac White
title: Zac White
description: Code, Snippets, Tips & Tricks
meta_description: "Co-Founder, Velos Mobile. Developer, San Francisco."

aboutPage: true

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
paginate: 5
paginate_path: '/posts/page:num/'
domain_name: 'https://zacwhite.com'
google_analytics: 'UA-73050-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

twitter:
  username: zacwhite
  card: summary

social:
  name: Zac White
  links:
    - https://twitter.com/zacwhite
    - https://www.facebook.com/zacwhite
    - https://www.instagram.com/zacwhite
    - https://www.linkedin.com/in/zacwhite
    - https://github.com/zac

# Details for the RSS feed generator
url:            'https://zacwhite.com'
author:         'Zac White'
authorTwitter:  'zacwhite'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
